{% set name = "echopop" %}
{% set version = "0.4.2" %}

package:
  name: echopop
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/echopop-{{ version }}.tar.gz
  sha256: 96322a4fafeeb836534fa2a8bd9edad7287c1e5bfb3982fa09525ce1c1c154f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=48
    - setuptools-scm >=4,<6
    - setuptools_scm_git_archive
    - wheel >=0.29.0
    - pip
  run:
    - geopandas
    - geopy
    - ipympl
    - ipywidgets
    - jupyter_contrib_nbextensions
    - lmfit
    - numpy
    - pandas
    - pandera
    - pydantic
    - python >=3.9
    - scipy
    - shapely
    - traitlets

test:
  imports:
    - echopop
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OSOceanAcoustics/echopop
  summary: A tool to generate biological estimates from acoustic data collected from echosounders
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://echopop.readthedocs.io/en/latest/
  dev_url: https://github.com/OSOceanAcoustics/echopop

extra:
  recipe-maintainers:
    - leewujung
    - brandynlucca
