{% set name = "echopop" %}
{% set version = "0.6.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/echopop-{{ version }}.tar.gz
  sha256: d976d22e31093f840cecb533c34242be1ac503c12124379ded72f6552c0a707e

build:
  noarch: python
  script: 
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - setuptools-scm >=8 
    - wheel >=0.29.0
    - pip
  run:
    - python >={{ python_min }}
    - awkward
    - bokeh
    - cartopy
    - geopandas
    - geopy
    - geoviews
    - holoviews
    - hvplot
    - ipympl
    - ipywidgets
    - matplotlib-base
    - jupyter_bokeh >=3.0.5
    - lmfit
    - numba >=0.63.0b1
    - numpy
    - openpyxl
    - pandas
    - pandera >=0.25
    - pyarrow
    - pydantic >=2.0.0
    - pyproj
    - scipy
    - seaborn
    - shapely
    - traitlets
    - verde
    - xarray >=2026.01.0

test:
  imports:
    - echopop
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/OSOceanAcoustics/echopop
  summary: A tool to generate biological estimates from acoustic data collected from echosounders
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://echopop.readthedocs.io/en/latest/
  dev_url: https://github.com/OSOceanAcoustics/echopop

extra:
  recipe-maintainers:
    - leewujung
    - brandynlucca
